//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public int EventId { get; set; }
        public string EventCode { get; set; }
        public string EventName { get; set; }
        public System.DateTime EventDate { get; set; }
        public string DistanceCategories { get; set; }
        public string EventCity { get; set; }
        public string EventState { get; set; }
        public string EventCountry { get; set; }
        public string EventDetails { get; set; }
        public string EventLocation { get; set; }
        public decimal RegistrationFees { get; set; }
        public string RegistrationLink { get; set; }
    }
}
